name: directus
description: The unofficial SDK for Directus, provides REST API and authentication. Requires Flutter.
version: 0.9.5
homepage: https://www.directus.io
repository: https://github.com/apstanisic/directus-dart
issue_tracker: https://github.com/apstanisic/directus-dart/issues

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  directus_core:
    git:
      url: https://github.com/mbenyoub/directus-dart.git
      path: packages/directus_core
  # Storage
  # shared_preferences: ^2.0.15
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
